name: Deploy

on:
  push:
    branches:
      - master
      - beta

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  REACT_APP_SENTRY_RELEASE: ${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Node install
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Dependencies
      run: yarn install

    - name: Test
      run: yarn test

    - name: Lint
      run: yarn lint

    - name: Build
      run: yarn build

    - name: Release
      run: yarn release

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: build-files
        path: ./out

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Download
      uses: actions/download-artifact@v2
      with:
        name: build-files
        path: ./out

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        cname: ${{ github.ref == 'ref/head/master' && 'app' || 'test' }}.2pi.finance
        publish_branch: pages
        publish_dir: ./out
